### ISSUE TITLE
wide character support in fasm

### ISSUE THREAD

**Issue by bitRAKE** [The-Z-Labs/bof-launcher#2]
https://github.com/The-Z-Labs/bof-launcher/blob/5d33547fb56bdaaa97f0599b6a7a3198db3fb155/bofs/src/wDirectSyscall.asm#L44-L48
This is the typical way to generate UTF-16 characters, assuming the source code is utf-8 encoded (in this case it doesn't matter because the filename is ASCII).
```assembly
include 'encoding/utf8.inc'
align 8
filename du 'file.txt'
    .SIZE = $ - filename
```

**Comment by bitRAKE** [comment]
Oh, just realized you probably don't want the dependency.

**Comment by michal-z** [comment]
@bitRAKE Thanks for the suggestion but yes you're right, we would prefer to avoid the dependency for now.
